theme: jekyll-theme-minimal
author: Yi-Shen Chen
title: Yi-Shen Chen
logo: "face.png"
description: Life is the art of drawing sufficient conclusions from insufficient premises.
email: "yschen195@iis.sinica.edu.tw"
url: "https://yschen195.github.io"
