theme: jekyll-theme-minimal
github:
  is_project_page: false
author: Yi-Shen Chen (陳奕伸)
title: Yi-Shen Chen (陳奕伸)
tagline: Assistant Professor @ Department of Electronic and Computer Engineering, National Taiwan University of Science and Technology
logo: "avatar.jpg"
description: Life is the art of drawing sufficient conclusions from insufficient premises.
email: "yschen195@iis.sinica.edu.tw"
url: "https://yschen195.github.io"
copyright: "2023"
show_downloads: false
