theme: jekyll-theme-minimal
title: Yi-Shen Chen
description: Life is the art of drawing sufficient conclusions from insufficient premises.

avatar:
  # Replace the default image and set the url here.
  url: /face.png
  # If true, the avatar will be dispalyed in circle.
  rounded: true
  # If true, the avatar will be rotated with the cursor.
  rotated: false
