theme: jekyll-theme-minimal
github:
  is_project_page: false
author: Yi-Shen Chen
title: Yi-Shen Chen  
陳奕伸
tagline: PostDoc @ IIS, Academia Sinica
logo: "avatar.jpg"
description: Life is the art of drawing sufficient conclusions from insufficient premises.
email: "yschen195@iis.sinica.edu.tw"
url: "https://yschen195.github.io"
copyright: "2023"
show_downloads: false
